FROM registry.fedoraproject.org/fedora-toolbox:37

RUN dnf install -y \
    @development-tools \
    gcc-c++ \
    glibc-langpack-tr \
    moreutils \
    neofetch \
    httpie \
    neovim \
    htop \
    btop \
    exa \
    jq \
    the_silver_searcher \
    bat \
    fish \
    podman \
    podman-compose \
    bind-utils \
    telnet \
    nodejs \
    npm \
    asciinema \
    ripgrep \
    fzf
